logLevel: trace
payloads:
 #- id: 1
 #  devDesc: 0x00010000
 #  type: EnrollFace
 #  inputData: '{"url":"http://192.168.8.12:4000/files/26da95b177cdbd470903b7c247665576","sourceType":"application/zip","libraryId":"10"}'
 - id: 2
   devDesc: 0x00020000
   type: VideoFaceRecognize
   inputData: '{"url": "rtsp://admin:lx123456@192.168.8.10:554/Streaming/Channels/301?transportmode=unicast",
      "cameraId": "10",
      "targetFaceRepoCompare": "true",
      "targetFaceRepoId": "1232",
      "capturedFaceSave": "true",
      "capturedFaceRepoId": "3423432"}'
 - id: 3
   devDesc: 0x00020000
   type: VideoFaceRecognize
   inputData: '{"url": "rtsp://admin:lx123456@192.168.8.10:554/Streaming/Channels/301?transportmode=unicast",
      "cameraId": "11",
      "targetFaceRepoCompare": "false",
      "capturedFaceSave": "false"}'

